config/routes.rb
Reservation::Application.routes.draw do
  resources :timeslots

  resources :tables

  resources :venues

  root to: "main#index"

  resources :appointments, :defaults => { :format => 'json' }

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :name
  has_many :tables
  has_many :appointments, :through => :tables
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.json
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.json
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.haml
= form_for @venue do |f|
  - if @venue.errors.any?
    #error_explanation
      %h2= "#{pluralize(@venue.errors.count, "error")} prohibited this venue from being saved:"
      %ul
        - @venue.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/venues/edit.html.haml
%h1 Editing venue

= render 'form'

= link_to 'Show', @venue
\|
= link_to 'Back', venues_path

app/views/venues/index.html.haml
%h1 Listing venues

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @venues.each do |venue|
    %tr
      %td= venue.name
      %td= link_to 'Show', venue
      %td= link_to 'Edit', edit_venue_path(venue)
      %td= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Venue', new_venue_path

app/views/venues/new.html.haml
%h1 New venue

= render 'form'

= link_to 'Back', venues_path

app/views/venues/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @venue.name

= link_to 'Edit', edit_venue_path(@venue)
\|
= link_to 'Back', venues_path