config/routes.rb
Reservation::Application.routes.draw do
  resources :timeslots

  resources :tables

  resources :venues

  root to: "main#index"

  resources :appointments, :defaults => { :format => 'json' }

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.haml
= form_for @table do |f|
  - if @table.errors.any?
    #error_explanation
      %h2= "#{pluralize(@table.errors.count, "error")} prohibited this table from being saved:"
      %ul
        - @table.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :seats
    = f.number_field :seats
  .field
    = f.label :venue_id
    = f.number_field :venue_id
  .field
    = f.label :appointment_id
    = f.number_field :appointment_id
  .actions
    = f.submit 'Save'

app/views/tables/edit.html.haml
%h1 Editing table

= render 'form'

= link_to 'Show', @table
\|
= link_to 'Back', tables_path

app/views/tables/index.html.haml
%h1 Listing tables

%table
  %tr
    %th Seats
    %th Venue
    %th Appointment
    %th
    %th
    %th

  - @tables.each do |table|
    %tr
      %td= table.seats
      %td= table.venue_id
      %td= table.appointment_id
      %td= link_to 'Show', table
      %td= link_to 'Edit', edit_table_path(table)
      %td= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Table', new_table_path

app/views/tables/new.html.haml
%h1 New table

= render 'form'

= link_to 'Back', tables_path

app/views/tables/show.html.haml
%p#notice= notice

%p
  %b Seats:
  = @table.seats
%p
  %b Venue:
  = @table.venue_id
%p
  %b Appointment:
  = @table.appointment_id

= link_to 'Edit', edit_table_path(@table)
\|
= link_to 'Back', tables_path