config/routes.rb
Reservation::Application.routes.draw do
  resources :timeslots

  resources :tables

  resources :venues

  root to: "main#index"

  resources :appointments, :defaults => { :format => 'json' }

end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  belongs_to :appointment
  belongs_to :table
  attr_accessible :hour
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  # GET /timeslots
  # GET /timeslots.json
  def index
    @timeslots = Timeslot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timeslots }
    end
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timeslot }
    end
  end

  # GET /timeslots/new
  # GET /timeslots/new.json
  def new
    @timeslot = Timeslot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeslot }
    end
  end

  # GET /timeslots/1/edit
  def edit
    @timeslot = Timeslot.find(params[:id])
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(params[:timeslot])

    respond_to do |format|
      if @timeslot.save
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully created.' }
        format.json { render json: @timeslot, status: :created, location: @timeslot }
      else
        format.html { render action: "new" }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timeslots/1
  # PUT /timeslots/1.json
  def update
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      if @timeslot.update_attributes(params[:timeslot])
        format.html { redirect_to @timeslot, notice: 'Timeslot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot = Timeslot.find(params[:id])
    @timeslot.destroy

    respond_to do |format|
      format.html { redirect_to timeslots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/timeslots/_form.html.haml
= form_for @timeslot do |f|
  - if @timeslot.errors.any?
    #error_explanation
      %h2= "#{pluralize(@timeslot.errors.count, "error")} prohibited this timeslot from being saved:"
      %ul
        - @timeslot.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :hour
    = f.number_field :hour
  .field
    = f.label :appointment
    = f.text_field :appointment
  .field
    = f.label :table
    = f.text_field :table
  .actions
    = f.submit 'Save'

app/views/timeslots/edit.html.haml
%h1 Editing timeslot

= render 'form'

= link_to 'Show', @timeslot
\|
= link_to 'Back', timeslots_path

app/views/timeslots/index.html.haml
%h1 Listing timeslots

%table
  %tr
    %th Hour
    %th Appointment
    %th Table
    %th
    %th
    %th

  - @timeslots.each do |timeslot|
    %tr
      %td= timeslot.hour
      %td= timeslot.appointment
      %td= timeslot.table
      %td= link_to 'Show', timeslot
      %td= link_to 'Edit', edit_timeslot_path(timeslot)
      %td= link_to 'Destroy', timeslot, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Timeslot', new_timeslot_path

app/views/timeslots/new.html.haml
%h1 New timeslot

= render 'form'

= link_to 'Back', timeslots_path

app/views/timeslots/show.html.haml
%p#notice= notice

%p
  %b Hour:
  = @timeslot.hour
%p
  %b Appointment:
  = @timeslot.appointment
%p
  %b Table:
  = @timeslot.table

= link_to 'Edit', edit_timeslot_path(@timeslot)
\|
= link_to 'Back', timeslots_path